manageAppointments/manageAppointments/urls.py
from django.contrib import admin  
from django.urls import path
from appointments import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.show) ,
    path('appform', views.appform , name="appform"),
    path('show',views.show, name="show"),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
    path('calender', views.calender, name="calender") ,
    path('fullreport/<int:id>' , views.fullreport , name = "fullreport"),
    path('sendmail/<int:id>' , views.sendmail , name = "sendmail"),
    path('fullrecords' , views.fullrecords , name="fullrecords"),
]  

manageAppointments/appointments/models.py
from django.db import models  
class Appointments(models.Model):  
    Appoint_ID = models.CharField(max_length=20)  
    Ap_Cus_name = models.CharField(max_length=200)  
    Ap_Cus_address = models.CharField(max_length=200) 
    Ap_Cus_email = models.EmailField()
    Ap_Purpose = models.CharField(max_length=200)
    Ap_Notes = models.CharField(max_length=200)
    Ap_Date_time = models.DateTimeField(default='2015-05-11 13:01:01')
    Ap_Venue = models.CharField(max_length=200)
    class Meta:  
        db_table = "App_details" 

manageAppointments/appointments/forms.py
from django import forms
from django.core import validators
from appointments.models import Appointments

#form to enter appointment
class AppointForm(forms.ModelForm):  
    class Meta:  
        model = Appointments  
        fields = "__all__"

manageAppointments/appointments/views.py
from django.shortcuts import render, redirect  
from appointments.forms import AppointForm  
from appointments.models import Appointments
from . import forms
from django.core.mail import send_mail


#function request form
def appform(request):  
    if request.method == "POST":  
        form = AppointForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = AppointForm()  
    return render(request,'app_form.html',{'form':form}) 

#function to display the dashboard
def show(request):  
    appointments = Appointments.objects.all()  
    return render(request,'dashboard.html',{'appointments':appointments}) 

#function to edit record
def edit(request, id):  
    appointment = Appointments.objects.get(id=id)  
    return render(request,'edit.html',{'appointment':appointment})  

#function  to update record
def update(request, id):  
    appointment = Appointments.objects.get(id=id)   
    form = AppointForm(request.POST, instance = appointment)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'appointment':appointment}) 

#function to delete record
def destroy(request, id):  
    appointment = Appointments.objects.get(id=id)  
    appointment.delete()  
    return redirect("/show")  

#function to call calender
def calender(request):
    return render(request, 'calender.html')

#function to watch the full report

def fullreport(request , id):
     appointment = Appointments.objects.get(id=id)  
     return render(request,'report.html',{'appointment':appointment})

#function to analyse full records
def fullrecords(request):
    appointments = Appointments.objects.all()  
    return render(request,'fullrecords.html',{'appointments':appointments})
    
#function to send emails
def sendmail(request, id):
    appointment = Appointments.objects.get(id=id)
    #send email
    send_mail(
    'About the appointment',
    'Dear Sir/Madam,Here is the summary of your appointment.'+
    'Venue ' +  appointment.Ap_Venue +
    'Purpose ' + appointment.Ap_Purpose + 
    'Extra Notes ' + appointment.Ap_Notes,
    'shashibandarass@gmail.com',
    [appointment.Ap_Cus_email],
    fail_silently=False,
    )
    return render(request,'report.html',{'appointment':appointment})
    

manageAppointments/appointments/templates/calender.html
<!DOCTYPE html>
{% load static %}
<html>
<head>


<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
<script src="{% static '/js/calender.js' %}"></script>
<link href="{% static '/css/calender.css' %}" rel="stylesheet" />
<script>

	$(document).ready(function() {
	    var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();
	
		$('#external-events div.external-event').each(function() {
	
			var eventObject = {
				title: $.trim($(this).text())
			};
			
			// store the Event Object in the DOM element so we can get to it later
			$(this).data('eventObject', eventObject);
			
			// make the event draggable using jQuery UI
			$(this).draggable({
				zIndex: 999,
				revert: true,      // will cause the event to go back to its
				revertDuration: 0  //  original position after the drag
			});
			
		});
	
		/*initializing the calendar*/
		var calendar =  $('#calendar').fullCalendar({
			header: {
				left: 'title',
				center: 'agendaDay,agendaWeek,month',
				right: 'prev,next today'
			},
			editable: true,
			firstDay: 1,
			selectable: true,
			defaultView: 'month',
			
			axisFormat: 'h:mm',
			columnFormat: {
                month: 'ddd',    
                week: 'ddd d',
                day: 'dddd M/d',  
                agendaDay: 'dddd d'
            },
            titleFormat: {
                month: 'MMMM yyyy', 
                week: "MMMM yyyy", 
                day: 'MMMM yyyy'                  
            },
			allDaySlot: false,
			selectHelper: true,
			select: function(start, end, allDay) {
				var title = prompt('Event Title:');
				if (title) {
					calendar.fullCalendar('renderEvent',
						{
							title: title,
							start: start,
							end: end,
							allDay: allDay
						},
						true 
					);
				}
				calendar.fullCalendar('unselect');
			},
			droppable: true, 
			drop: function(date, allDay) { 
			
				// retrieve the dropped element's stored Event Object
				var originalEventObject = $(this).data('eventObject');
				
				// we need to copy it, so that multiple events don't have a reference to the same object
				var copiedEventObject = $.extend({}, originalEventObject);
				
				// assign it the date that was reported
				copiedEventObject.start = date;
				copiedEventObject.allDay = allDay;
				
				// render the event on the calendar
				$('#calendar').fullCalendar('renderEvent', copiedEventObject, true);
				
				
				// is the "remove after drop" checkbox checked?
				if ($('#drop-remove').is(':checked')) {
					// if so, remove the element from the "Draggable Events" list
					$(this).remove();
				}
				
			},
			
			events: [
				{
					title: 'All Day Event',
					start: new Date(y, m, 1)
				},
				{
					id: 999,
					title: 'Repeating Event',
					start: new Date(y, m, d-3, 16, 0),
					allDay: false,
					className: 'info'
				},
				{
					id: 999,
					title: 'Repeating Event',
					start: new Date(y, m, d+4, 16, 0),
					allDay: false,
					className: 'info'
				},
				{
					title: 'Meeting',
					start: new Date(y, m, d, 10, 30),
					allDay: false,
					className: 'important'
				},
				{
					title: 'Lunch',
					start: new Date(y, m, d, 12, 0),
					end: new Date(y, m, d, 14, 0),
					allDay: false,
					className: 'important'
				},
				{
					title: 'Birthday Party',
					start: new Date(y, m, d+1, 19, 0),
					end: new Date(y, m, d+1, 22, 30),
					allDay: false,
				},
				
			],			
		});
		
		
	});

//convert into JSON file
 var ebemtObject = JSON.parse('{ "title": "Click for Google", "start": "new Date(y, m, 28)", "end": "new Date(y, m, 28)", "url": "https://www.google.com/", "className": "success" }');

</script>
<style>

	body {
	    margin-bottom: 40px;
		margin-top: 40px;
		text-align: center;
		font-size: 14px;
		font-family: 'Roboto', sans-serif;
		background:url(http://www.digiphotohub.com/wp-content/uploads/2015/09/bigstock-Abstract-Blurred-Background-Of-92820527.jpg);
		}
		
	#wrap {
		width: 1100px;
		margin: 0 auto;
		}
		
	#external-events {
		float: left;
		width: 150px;
		padding: 0 10px;
		text-align: left;
		}
		
	#external-events h4 {
		font-size: 16px;
		margin-top: 0;
		padding-top: 1em;
		}
		
	.external-event { /* try to mimick the look of a real event */
		margin: 10px 0;
		padding: 2px 4px;
		background: #3366CC;
		color: #fff;
		font-size: .85em;
		cursor: pointer;
		}
		
	#external-events p {
		margin: 1.5em 0;
		font-size: 11px;
		color: #666;
		}
		
	#external-events p input {
		margin: 0;
		vertical-align: middle;
		}

	#calendar {
/* 		float: right; */
        margin: 0 auto;
		width: 900px;
		background-color: #FFFFFF;
		  border-radius: 6px;
        box-shadow: 0 1px 2px #C3C3C3;
		-webkit-box-shadow: 0px 0px 21px 2px rgba(0,0,0,0.18);
-moz-box-shadow: 0px 0px 21px 2px rgba(0,0,0,0.18);
box-shadow: 0px 0px 21px 2px rgba(0,0,0,0.18);
		}

</style>
</head>
<body>
<div id='wrap'>
<a href="{% url 'show' %}"><button type="button" class="btn btn-primary btn-lg">Go to Dashboard</button></a>
<a href="{% url 'appform' %}"><button type="button" class="btn btn-secondary btn-lg">Go to Forms</button></a>
<div id='calendar'></div>

<div style='clear:both'></div>
</div>
</body>
</html>

manageAppointments/appointments/templates/edit.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Edit</title>

    <link href="{% static '/css/style.css' %}" rel="stylesheet" />
    <link href="{% static '/css/appform.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-light bg-light">
    <a class="navbar-brand" href="dashboard.html">Home</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
      <!-- Other Links -->
           <a  href="{% url 'appform' %}" class="nav-link">
                 Enter am appointment 
            </a>
            <a href="{% url 'calender' %}" class="nav-link" >
                 Appointment Calender 
            </a>
            <a  href="{% url 'fullrecords' %}" class="nav-link">
                  Generate Reports 
            </a>

    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">Settings</a>
                <a class="dropdown-item" href="#">Activity Log</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="login.html">Logout</a>
            </div>
        </li>
    </ul>
</nav>

<!-- end of the header nav bar -->

<!--side nav Bar -->
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
            <div class="sb-sidenav-menu ">
                <div class="nav">
                    <!-- Customer Information -->
                     <a class="nav-link" href="dashboard.html">
                                <div class="sb-nav-link-icon"> 
                                 <img src="{% static '/images/check-circle.gif' %}"  style="width: 20px; height: 20px;"/>
                                </div>
                                Customer Information
                            </a>

                            <a class="nav-link" href="{% url 'show' %}">
                                <div class="sb-nav-link-icon">
                                    <img src="{% static '/images/check-circle.gif' %}"  style="width: 20px; height: 20px;"/>
                                </div>
                                Appointments
                            </a>

                            <a class="nav-link" href="dashboard.html">
                                <div class="sb-nav-link-icon">
                                  <img src="{% static '/images/check-circle.gif' %}"  style="width: 20px; height: 20px;"/>
                                </div>
                                Work Progress
                            </a>

                            <a class="nav-link" href="dashboard.html">
                                <div class="sb-nav-link-icon">  
                                <img src="{% static '/images/check-circle.gif' %}"  style="width: 20px; height: 20px;"/>
                                </div>
                                Service List
                            </a>

                            <a class="nav-link" href="dashboard.html">
                                <div class="sb-nav-link-icon">
                                  <img src="{% static '/images/check-circle.gif' %}"  style="width: 20px; height: 20px;"/>
                                </div>
                                Invoice
                            </a>

                            <a class="nav-link" href="dashboard.html">
                                <div class="sb-nav-link-icon">
                                    <img src="{% static '/images/check-circle.gif' %}"  style="width: 20px; height: 20px;"/>
                                </div>
                                Prepare Reciepts
                            </a>

                            <a class="nav-link" href="dashboard.html">
                                <div class="sb-nav-link-icon">  
                                   <img src="{% static '/images/check-circle.gif' %}"  style="width: 20px; height: 20px;"/>
                                </div>
                                Prepare Documents
                            </a>

                </div>
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 offset-3 float-md-center jumbcont">
                <div class="jumbotron jumbotron-fluid jumb1">
                    <div class="container">
                        <h4 class="display-4">Edit Appointment Details</h4>

                             <form method="POST" action="/update/{{appointment.id}}" class="post-form" >  
                                {% csrf_token %}
                                <!--Appointment ID-->
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Appointment ID</label>
                                       <div class="col-sm-10">
                                    <input type="text" class="form-control" id="id_Appoint_ID" name="Appoint_ID" value="{{ appointment.Appoint_ID }}">
                                     </div>
                                 </div>
                                <!-- Customer Name -->
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Name</label>
                                       <div class="col-sm-10">
                                       <input type="text" class="form-control" id="id_Ap_Cus_name" name="Ap_Cus_name" value="{{ appointment.Ap_Cus_name }}">
                                     </div>
                                 </div>
                                 <!-- Address -->
                                <div class="form-group row">
                                    <label for="inputPassword" class="col-sm-2 col-form-label">Address</label>
                                       <div class="col-sm-10">
                                       <input type="text" class="form-control" id="id_Ap_Cus_address" name="Ap_Cus_address" value="{{ appointment.Ap_Cus_address}}">
                                     </div>
                                 </div>
                                  <!-- Email-->
                                <div class="form-group row">
                                    <label   class="col-sm-2 col-form-label">Email</label>
                                       <div class="col-sm-10">
                                       <input type="text" class="form-control" id="id_Ap_Cus_email" name="Ap_Cus_email" value="{{ appointment.Ap_Cus_email }}">
                                     </div>
                                 </div>
                                  <!-- Purpose -->
                                <div class="form-group row">
                                    <label  class="col-sm-2 col-form-label">Purpose</label>
                                       <div class="col-sm-10">
                                       <input type="text" class="form-control" id="id_Ap_Purpose" name="Ap_Purpose" value="{{ appointment.Ap_Purpose }}">
                                     </div>
                                 </div>

                               <!-- date and time -->
                                <div class="form-group row">
                                    <label  class="col-sm-2 col-form-label">Date and Time</label>
                                       <div class="col-sm-10">
                                       <input type="text" class="form-control" id="id_Ap_Date_time" name="Ap_Date_time" value="{{ appointment.Ap_Date_time }}">
                                     </div>
                                 </div>
                                 
                                <!--Additonal notes-->
                                <div class="form-group row">
                                    <label  class="col-sm-2 col-form-label">Additional Notes</label>
                                       <div class="col-sm-10">
                                       <input type="text" class="form-control" id="id_Ap_Notes" name="Ap_Notes" value="{{ appointment.Ap_Notes}}">
                                     </div>
                                 </div>
                                <!-- Venue -->
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Place/Venue</label>
                                       <div class="col-sm-10">
                                       <input type="text" class="form-control" id="id_Ap_Venue" name="Ap_Venue" value="{{ appointment.Ap_Venue }}">
                                     </div>
                                 </div>
                                    <button type="submit" class="btn btn-success" style="margin-left : 250px;">Update</button>  
                              </form>

                    </div>
                </div>
            </div>
        </main>
    </div>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; ShrimaliS</div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="{% static '/js/scripts.js' %}"></script>

<!--Validations-->
<script>
</script>

</body>
</html>

manageAppointments/appointments/templates/fullrecords.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>All records</title>

        <link href="{% static '/css/style.css' %}" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'show' %}">Home</a>
            <!-- Other Links -->
            <a  href="{% url 'appform' %}" class="nav-link">
                 Enter am appointment 
            </a>
            <a href="{% url 'calender' %}" class="nav-link" >
                 Appointment Calender 
            </a>
            <a  href="{% url 'fullrecords' %}" class="nav-link">
                  Generate Reports 
            </a>

            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <div class="input-group">
                    <div class="input-group-append">
                        <a href="https://www.google.com/"><button type="button" class="btn btn-primary">Search google! <i class="fas fa-search"></i></button></a>
                    </div>
                </div>
            </form>

            <!-- Navbar-->
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">Settings</a>
                        <a class="dropdown-item" href="#">Activity Log</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="login.html">Logout</a>
                    </div>
                </li>
            </ul>
        </nav>

        <!-- end of the header nav bar -->

            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid" style="margin-top: 30px; margin-left: 40px;">
                        <div class="row">
                        <div class="card mb-4"  style="margin-top: 50px;">
                            <div class="card-header">
                                <i class="fas fa-table mr-1"></i>
                                Data table
                            </div>
                            <div class="card-body" style="margin-top: 5px; margin-left: 50px">
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Name</th>
                                                <th>Purpose</th>
                                                <th>Date and Time</th>
                                                <th>Send Prior Email</th>
                                                <th>Make Changes</th>
                                                <th>Watch</th>
                                            </tr>
                                        </thead>
                                        <tfoot>
                                            <tr>
                                                <th>Record ID</th>
                                                <th>Name</th>
                                                <th>Purpose</th>
                                                <th>Date and Time</th>
                                                <th>Send Prior Email</th>
                                                <th>Make Changes</th>
                                                <th>Watch</th>
                                            </tr>
                                        </tfoot>
                                        <tbody>
                                        
										{% for appointment in appointments %}
                                            <tr>
                                                <td>{{ appointment.id }}</td>
                                                <td>{{ appointment.Ap_Cus_name }}</td>
                                                <td>{{appointment.Ap_Purpose}}</td>
                                                <td>{{ appointment.Ap_Date_time }}</td>
                                                <td><i class="fas fa-paper-plane"></i></td>
                                                <td>
                                                    <a href="/edit/{{ appointment.id }}"> <i class="fas fa-pen"></i></a>
                                                    <a href="/delete/{{  appointment.id }}"> <i class="far fa-trash-alt"></i></a>
                                                </td>
                                                <td> <a href="/fullreport/{{  appointment.id }}"><i class="fa fa-eye" aria-hidden="true">
												</i></td></a>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted" style="text-align: center;">Copyright &copy; @ShrimaliS</div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static '/js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="{% static '/assets/demo/chart-bar-demo.js' %}"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="{% static '/assets/demo/datatables-demo.js' %}"></script>
        <script src="{% static '/assets/demo/chart-pie-demo.js' %}"></script>
    </body>
</html>